src/App/urls.py
from django.urls import path
from .views import EmailVerificationView, EmailSentView

app_name = "Email"

urlpatterns = [
	path('verify/', EmailVerificationView.as_view(), name='emailverification'),
	path('emailsent/', EmailSentView.as_view(), name='emailsent'),
]

src/Celery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
]

src/App/models.py
from django.db import models

# Create your models here.

src/App/forms.py
from django import forms
from .tasks import send_email_task

class EmailVerificationForm(forms.Form):
	name = forms.CharField(
		label='Firstname', 
		max_length=100, 
		widget=forms.TextInput(
			attrs={'class': 'form-control mb-3', 'placeholder': 'Name'}
			)
		)
	email = forms.EmailField(
		label='Email', 
		max_length=100, 
		widget=forms.TextInput(
			attrs={'class': 'form-control mb-3', 'placeholder': 'Email'}
			)
		)

	def send_email(self):
		email = self.cleaned_data['email']
		name = self.cleaned_data['name']

		send_email_task.delay(name, email)

src/App/views.py
from django.shortcuts import redirect
from django.views.generic.base import TemplateView
from .forms import EmailVerificationForm
from django.views.generic.edit import FormView


class EmailSentView(TemplateView):
	template_name = "App/EmailSent.html"


class EmailVerificationView(FormView):
	template_name = "App/VerifyEmail.html"
	form_class = EmailVerificationForm
 
	def form_valid(self, form):
		form.send_email()
		return redirect('Email:emailsent')

src/App/templates/App/EmailSent.html
{% extends "base.html" %}
{% block title %}Email Sent{% endblock %}
{% block content %}


<style>
	.login,
	.image {
		min-height: 100vh;
	}

	.bg-image {
		background-image: url('https://picsum.photos/id/1079/1080');
		background-size: cover;
		background-position: center center;
	}

	.container-fluid {
		max-width: 100%;
	}

	.account-form input {
		border: 2px solid #ccc;
		height: calc(2em + .75rem + 2px);
	}

	.account-form input:focus {
		border-color: #1497ff;
		box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
	}
</style>


<div class="container-fluid">
	<div class="row no-gutter">
		<div class="col-md-6 bg-light">
			<div class="login d-flex align-items-center py-5">
				<div class="container">
					<div class="row">
						<div class="col-8 col-md-8  mx-auto">
							<h3>Email Sent</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6 d-none d-md-flex bg-image"></div>
	</div>
</div>
{% endblock %}

src/App/templates/App/VerifyEmail.html
{% extends "base.html" %}
{% block title %}Email Verify{% endblock %}
{% block content %}


<style>
	.login,
	.image {
		min-height: 100vh;
	}

	.bg-image {
		background-image: url('https://picsum.photos/id/1079/1080');
		background-size: cover;
		background-position: center center;
	}

	.container-fluid {
		max-width: 100%;
	}

	.account-form input {
		border: 2px solid #ccc;
		height: calc(2em + .75rem + 2px);
	}

	.account-form input:focus {
		border-color: #1497ff;
		box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
	}
</style>


<div class="container-fluid">
	<div class="row no-gutter">
		<div class="col-md-6 bg-light">
			<div class="login d-flex align-items-center py-5">
				<div class="container">
					<div class="row">
						<div class="col-8 col-md-8  mx-auto">
							<p class="h4 mb-4 font-weight-bold">Provide your Email for activation</p>
							<form action="{% url 'Email:emailverification' %}" method="post">{% csrf_token %}
								{{ form.as_p }}
								<button class="btn btn-dark btn-block py-2 mb-4 mt-5 font-weight-bold"
									type="submit" value="Log-in">Submit</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6 d-none d-md-flex bg-image"></div>
	</div>
</div>
{% endblock %}

src/App/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <title>{% block title %} Welcome to blog {% endblock %}</title>

  <style>
    .small {
      font-size: 0.875rem;
      color: #4b4b4b;
    }
  </style>

</head>

<body>

  {% block content %}
  {% endblock %}


  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>
</body>

</html>